# Generated by Django 4.2.1 on 2023-05-06 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('follow_releated_search', models.BooleanField(default=False)),
                ('follow_ppl_also_ask', models.BooleanField(default=False)),
                ('max_results', models.PositiveIntegerField(default=10)),
                ('frequency', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subdomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submanage.subdomain')),
            ],
        ),
    ]
