# Generated by Django 4.2.1 on 2023-05-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submanage', '0002_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('post_author', models.BigIntegerField(default=0)),
                ('post_date', models.DateTimeField(default='0000-00-00 00:00:00')),
                ('post_date_gmt', models.DateTimeField(default='0000-00-00 00:00:00')),
                ('post_content', models.TextField()),
                ('post_title', models.TextField()),
                ('post_excerpt', models.TextField()),
                ('post_status', models.CharField(default='publish', max_length=20)),
                ('comment_status', models.CharField(default='open', max_length=20)),
                ('ping_status', models.CharField(default='open', max_length=20)),
                ('post_password', models.CharField(default='', max_length=255)),
                ('post_name', models.CharField(default='', max_length=200)),
                ('to_ping', models.TextField()),
                ('pinged', models.TextField()),
                ('post_modified', models.DateTimeField(default='0000-00-00 00:00:00')),
                ('post_modified_gmt', models.DateTimeField(default='0000-00-00 00:00:00')),
                ('post_content_filtered', models.TextField()),
                ('post_parent', models.BigIntegerField(default=0)),
                ('guid', models.CharField(default='', max_length=255)),
                ('menu_order', models.IntegerField(default=0)),
                ('post_type', models.CharField(default='post', max_length=20)),
                ('post_mime_type', models.CharField(default='', max_length=100)),
                ('comment_count', models.BigIntegerField(default=0)),
            ],
        ),
    ]
