# Generated by Django 4.2.1 on 2023-05-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submanage', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date_gmt',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_modified_gmt',
            field=models.DateTimeField(),
        ),
    ]
