# Generated by Django 4.2.1 on 2023-05-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submanage', '0005_alter_post_post_date_alter_post_post_date_gmt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_modified_gmt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
